apiVersion: apps/v1
kind: Deployment
metadata: 
  name: messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging 
    spec:
      containers:
        - name: meassaging-container
          image: messaging_app
          ports:
            - containerPort: 8000
