#!/bin/bash

# Script: kurbeScript
# Starts Minikube and verifies cluster status

echo "Checking of Minikube is installed..."
if ! command -v minikube &> /dev/null; then
    echo "Minikube not found. Please install it first: https://minikube.sigs.k8s.io/docs/start/"
    exit 1
fi

echo "Minikube is installed."

echo "Starting Minikube cluster..."
minikube start

if [ $? -ne 0 ]; then
    echo "Failed to start Minikube"
    exit 1
fi
echo "Minikube Started"

echo "Verifying Kubernetes cluster..."
kubectl cluster-info

if [ $? -ne 0 ]; then
    echo "Kubectl could not connect to the cluster"
    exit 1
fi
echo "Kubernetes cluster is up and running."

echo "Getting current pods in all namespaces..."
kubectl get pods --all-namespaces

echo "...Cluster Set and Started Successfull..."
